// lang.js
const translations = {
    en: {
      dashboard: "Dashboard",
      totalProduct: "Total Product",
      totalCustomer: "Total Customer",
      totalOrder: "Total Order",
      admin: "Admin",
      customer: "Customer",
      products: "Products",
      orders: "Orders",
      reports: "Reports",
      settings: "Settings",
      restock: "Restock",
      customerID: "Customer ID",
      contactNumber: "Contact Number",
      memberStatus: "Member Status",
      action: "Action",
      first: "First",
      previous: "Previous",
      next: "Next",
      last: "Last",
      adminID: "Admin ID",
      name: "Name",
      department: "Department",
      searchProduct: "Search product...",
      search: "Search",
      productID: "Product ID",
      series: "Series",
      all: "All",
      size: "Size",
      minPrice: "Min Price",
      maxPrice: "Max Price",
      applyFilter: "Apply Filter",
      productInfo: "Product Info",
      productName: "Product Name",
      seriesID: "Series ID",
      seriesName: "Series Name",
      sizeID: "Size ID",
      price: "Price (RM)",
      introduction: "Introduction",
      playerInfo: "Player Info",
      addProduct: "Add Product",
      images: "Images",
      productPicture: "Product Picture",
      dropProductImages: "Drag & drop product images here or click to select",
      noFileChosen: "No file chosen",
      playerPicture: "Player Picture",
      dropPlayerImages: "Drag & drop player images here or click to select",
      backProduct: "← Back Product",
      stock: "Stock",
      actions: "Actions",
      generateAdminReport: "Generate Admin Report",
      reportType: "Report Type:",
      selectReportType: "Select Report Type",
      from: "From:",
      to: "To:",
      generateReport: "Generate report",
      clearFilters: "Clear Filters",
      saveTemplate: "Save Template",
      welcome: "Welcome",
      loginPrompt: "Please login to your account",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
      username: "Username",
      password: "Password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      login: "Login",
      wrongLogin: "Wrong username or password",
      request: "Request",
      unblock: "Unblock",
      blockedMsg: "Sorry, you have been blocked by admin.",
      userID: "Your User ID:",
      priceSorting: "Price Sorting",
      lowToHigh: "Low to High",
      highToLow: "High to Low",
      priceRange: "Price Range",
      rmMin: "RM MIN",
      rmMax: "RM MAX",
      apply: "Apply",
      racketUser: "The player who is using this racket",
      racketIntro: "Racket Introduction ↓",
      grip: "Grip",
      joint: "Joint",
      tJoint: "T-joint",
      texture: "Texture",
      fullCarbon: "Full-carbon",
      itemID: "Item ID",
      required: "Required",
      cart: "Cart",
      review: "Review",
      shippingInfo: "Shipping Information",
      paymentMethods: "Payment Methods",
      creditCard: "Credit Card",
      onlineBanking: "Online Banking",
      checkoutSummary: "Checkout Summary",
      subtotal: "Subtotal",
      shipping: "Shipping",
      free: "Free",
      discount: "Discount",
      voucher: "Voucher",
      voucherCode: "Voucher Code",
      total: "Total",
      checkoutMsg: "You are minutes away from badminton awesomeness",
      publicProfile: "Public profile",
      personalDetails: "Personal details",
      accountSettings: "Account settings",
      privacySettings: "Privacy settings",
      savedAddress: "Saved address",
      email: "Email",
      bio: "Bio",
      gender: "Gender",
      female: "Female",
      male: "Male",
      ratherNotSay: "Rather not say",
      updateProfile: "Update profile",
      changePassword: "Change password",
      accountMaintenance: "Account maintenance",
      deleteAccount: "Delete account",
      alreadyHaveAccount: "Already have an account?",
      signIn: "Sign in",
    },
    zh: {
      dashboard: "仪表板",
      totalProduct: "商品总数",
      totalCustomer: "客户总数",
      totalOrder: "订单总数",
      admin: "管理员",
      customer: "客户",
      products: "商品",
      orders: "订单",
      reports: "报告",
      settings: "设置",
      restock: "补货",
      customerID: "客户编号",
      contactNumber: "联系电话",
      memberStatus: "会员状态",
      action: "操作",
      first: "首页",
      previous: "上一页",
      next: "下一页",
      last: "尾页",
      adminID: "管理员编号",
      name: "姓名",
      department: "部门",
      searchProduct: "搜索商品...",
      search: "搜索",
      productID: "商品编号",
      series: "系列",
      all: "全部",
      size: "尺寸",
      minPrice: "最小价格",
      maxPrice: "最大价格",
      applyFilter: "应用筛选",
      productInfo: "商品信息",
      productName: "商品名称",
      seriesID: "系列编号",
      seriesName: "系列名称",
      sizeID: "尺寸编号",
      price: "价格 (RM)",
      introduction: "介绍",
      playerInfo: "使用者信息",
      addProduct: "添加商品",
      images: "图片",
      productPicture: "商品图片",
      dropProductImages: "拖放商品图片或点击选择",
      noFileChosen: "未选择文件",
      playerPicture: "使用者图片",
      dropPlayerImages: "拖放使用者图片或点击选择",
      backProduct: "← 返回商品",
      stock: "库存",
      actions: "操作",
      generateAdminReport: "生成管理员报告",
      reportType: "报告类型：",
      selectReportType: "选择报告类型",
      from: "从：",
      to: "到：",
      generateReport: "生成报告",
      clearFilters: "清除筛选",
      saveTemplate: "保存模板",
      welcome: "欢迎",
      loginPrompt: "请登录您的账户",
      noAccount: "没有账户？",
      signUp: "注册",
      username: "用户名",
      password: "密码",
      rememberMe: "记住我",
      forgotPassword: "忘记密码？",
      login: "登录",
      wrongLogin: "用户名或密码错误",
      request: "请求",
      unblock: "解除封锁",
      blockedMsg: "对不起，您已被管理员封锁。",
      userID: "您的用户编号：",
      priceSorting: "价格排序",
      lowToHigh: "从低到高",
      highToLow: "从高到低",
      priceRange: "价格范围",
      rmMin: "最低 RM",
      rmMax: "最高 RM",
      apply: "应用",
      racketUser: "使用该球拍的球员",
      racketIntro: "球拍介绍 ↓",
      grip: "握把",
      joint: "接头",
      tJoint: "T型接头",
      texture: "材质",
      fullCarbon: "全碳素",
      itemID: "项目编号",
      required: "必填",
      cart: "购物车",
      review: "评论",
      shippingInfo: "配送信息",
      paymentMethods: "付款方式",
      creditCard: "信用卡",
      onlineBanking: "网上银行",
      checkoutSummary: "结账摘要",
      subtotal: "小计",
      shipping: "配送",
      free: "免费",
      discount: "折扣",
      voucher: "优惠券",
      voucherCode: "优惠码",
      total: "总计",
      checkoutMsg: "你离羽球精彩仅一步之遥",
      publicProfile: "公开资料",
      personalDetails: "个人信息",
      accountSettings: "账户设置",
      privacySettings: "隐私设置",
      savedAddress: "保存的地址",
      email: "电子邮件",
      bio: "简介",
      gender: "性别",
      female: "女",
      male: "男",
      ratherNotSay: "不愿透露",
      updateProfile: "更新资料",
      changePassword: "更改密码",
      accountMaintenance: "账户维护",
      deleteAccount: "删除账户",
      alreadyHaveAccount: "已有账户？",
      signIn: "登录",
    },
    ms: {
      dashboard: "Papan Pemuka",
      totalProduct: "Jumlah Produk",
      totalCustomer: "Jumlah Pelanggan",
      totalOrder: "Jumlah Pesanan",
      admin: "Admin",
      customer: "Pemuka Pelanggan",
      products: "Produk",
      orders: "Pesanan",
      reports: "Laporan",
      settings: "Tetapan",
      restock: "Restok",
      customerID: "ID Pelanggan",
      contactNumber: "Nombor Telefon",
      memberStatus: "Status Ahli",
      action: "Tindakan",
      first: "Pertama",
      previous: "Sebelum",
      next: "Seterusnya",
      last: "Terakhir",
      adminID: "ID Admin",
      name: "Nama",
      department: "Jabatan",
      searchProduct: "Cari produk...",
      search: "Cari",
      productID: "ID Produk",
      series: "Siri",
      all: "Semua",
      size: "Saiz",
      minPrice: "Harga Min",
      maxPrice: "Harga Maks",
      applyFilter: "Guna Penapis",
      productInfo: "Maklumat Produk",
      productName: "Nama Produk",
      seriesID: "ID Siri",
      seriesName: "Nama Siri",
      sizeID: "ID Saiz",
      price: "Harga (RM)",
      introduction: "Pengenalan",
      playerInfo: "Maklumat Pemain",
      addProduct: "Tambah Produk",
      images: "Imej",
      productPicture: "Gambar Produk",
      dropProductImages: "Seret & lepaskan gambar produk di sini atau klik untuk pilih",
      noFileChosen: "Tiada fail dipilih",
      playerPicture: "Gambar Pemain",
      dropPlayerImages: "Seret & lepaskan gambar pemain di sini atau klik untuk pilih",
      backProduct: "← Kembali Produk",
      stock: "Stok",
      actions: "Tindakan",
      generateAdminReport: "Jana Laporan Admin",
      reportType: "Jenis Laporan:",
      selectReportType: "Pilih Jenis Laporan",
      from: "Dari:",
      to: "Hingga:",
      generateReport: "Jana laporan",
      clearFilters: "Kosongkan Penapis",
      saveTemplate: "Simpan Templat",
      welcome: "Selamat datang",
      loginPrompt: "Sila log masuk ke akaun anda",
      noAccount: "Tiada akaun?",
      signUp: "Daftar",
      username: "Nama pengguna",
      password: "Kata laluan",
      rememberMe: "Ingat saya",
      forgotPassword: "Lupa kata laluan?",
      login: "Log masuk",
      wrongLogin: "Nama pengguna atau kata laluan salah",
      request: "Permintaan",
      unblock: "Nyahsekat",
      blockedMsg: "Maaf, anda telah disekat oleh admin.",
      userID: "ID Pengguna Anda:",
      priceSorting: "Isih Harga",
      lowToHigh: "Rendah ke Tinggi",
      highToLow: "Tinggi ke Rendah",
      priceRange: "Julat Harga",
      rmMin: "RM Minimum",
      rmMax: "RM Maksimum",
      apply: "Guna",
      racketUser: "Pemain yang menggunakan raket ini",
      racketIntro: "Pengenalan Raket ↓",
      grip: "Cengkaman",
      joint: "Sambungan",
      tJoint: "Sambungan T",
      texture: "Tekstur",
      fullCarbon: "Karbon Penuh",
      itemID: "ID Item",
      required: "Wajib",
      cart: "Troli",
      review: "Ulasan",
      shippingInfo: "Maklumat Penghantaran",
      paymentMethods: "Kaedah Pembayaran",
      creditCard: "Kad Kredit",
      onlineBanking: "Perbankan Dalam Talian",
      checkoutSummary: "Ringkasan Pembayaran",
      subtotal: "Jumlah Kecil",
      shipping: "Penghantaran",
      free: "Percuma",
      discount: "Diskaun",
      voucher: "Baucar",
      voucherCode: "Kod Baucar",
      total: "Jumlah",
      checkoutMsg: "Anda hanya beberapa minit dari kehebatan badminton",
      publicProfile: "Profil umum",
      personalDetails: "Maklumat peribadi",
      accountSettings: "Tetapan akaun",
      privacySettings: "Tetapan privasi",
      savedAddress: "Alamat yang disimpan",
      email: "E-mel",
      bio: "Bio",
      gender: "Jantina",
      female: "Perempuan",
      male: "Lelaki",
      ratherNotSay: "Lebih suka tidak nyatakan",
      updateProfile: "Kemas kini profil",
      changePassword: "Tukar kata laluan",
      accountMaintenance: "Penyelenggaraan akaun",
      deleteAccount: "Padam akaun",
      alreadyHaveAccount: "Sudah ada akaun?",
      signIn: "Log masuk",
    }
  };
  
  
  function switchLanguage(lang) {
    const elements = document.querySelectorAll('[data-language]');
    elements.forEach(el => {
      const key = el.getAttribute('data-language');
      el.textContent = translations[lang][key] || key;
    });
  
   //save language prefer
    localStorage.setItem('lang', lang);
  }
  
  function autoDetectLanguage() {
    const savedLang =
    localStorage.getItem('lang') ||
    (navigator.language.startsWith('zh') ? 'zh' :
     navigator.language.startsWith('ms') ? 'ms' : 'en');
  switchLanguage(savedLang);
  }
  